services:
  - type: web
    name: hrmsbackend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SPRING_MAIL_USERNAME
        value: aishushettar95@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: bbfskhrhtnujkokk
      - key: JWT_SECRET
        value: MyFixedSecretKey123456
      - key: PORT
        value: 8082
